### ISSUE TITLE
component testing

### ISSUE THREAD

**Issue by mikeshams** [karamjotkaur/capstone_project#1]
Gurdeep - What issues did you face when testing the components? How did you fix them?

**Comment by gurdeepsingh17** [comment]
Some of the issues I faced during the testing of components are written below
1) while trying to test the esp32 module, port 4 of the host machine was not working. It did not detect the esp32 so I have to change it to port 5. After changing the port the issue was resolved. 
2) After uploading the code to the esp32 module, there was a command on the monitor to press the reset button, when I pressed the reset button it didn't work. I checked youtube videos for its solution and finally resolved it.  The problem was with the baud rate. we have to set the same baud rate for Arduino ide and esp32.
3) I was not able to test the DC motor because output was not coming as expected. That was due to the connection problem, the wires were loose so I fixed them, and then it started working perfectly. I have to attach an external battery also.
4) while testing the temperature sensor MLX90614, all the references available on different sites were with a chip attached to the sensor, but our sensor was without a chip so I have to check the datasheet to understand its pin description. A website showed the wrong pin description of the sensor, due to which initially I didn't get any output, after checking another website, I corrected the connection and got the right results.
