### ISSUE TITLE
interfacing the LCD Display

### ISSUE THREAD

**Issue by mikeshams** [karamjotkaur/capstone_project#10]
Karamjot - 1) What issues did you encounter when interfacing the LCD Display? 2) How did you resolve them? 3) Can you use your LCD Display in 8-bit mode? 4) How? 5) If yes, what are the consequences in your project? 6) If somebody wants to change the font size what LCD Display do you recommend?

**Comment by karamjotkaur** [comment]
The interfacing of LCD with Beagle Bone Black was successful as I was able to show the number of customers present in the store. During this interfacing, I faced some issues that are as follow:
a. interfacing LCD with Beagle Bone Black using C code was difficult as there was very little information about it.
b. Moreover, jumper wires were loose due to which one ultrasonic sensor was not detecting a hand's presence.

So, to make interfacing working, I searched and tried numerous codes until one of them worked as per our requirements. In addition to this, I also changed the jumper wires and made connections proper to get the desired output.

Technically, the LCD can operate in 8-bit mode. For this purpose, we need all 8 pins of LCD, so we send a byte at once. Instead of initialing the LCD with the 0x20 command, we have to use 0x30 and 0x38, which stands for 8-bit mode and 2 lines, respectively. In our project, we are using an LCD with the pcf8574 module.  It converts the parallel interfacing into serial one, and we need only two wires SDA and SCL, apart from power connections. Here, we are sending data using these pins. We have masked the b-bit data and sent a nibble to LCD.

We are using an I2C communication protocol between an LCD and Beagle Bone Black, and we were looking forward to saving the pins of BBB. A 4bit mode works fine for our project.

If someone wants to change the font of LCD, they can use 129x64 graphic VFD. It is from Adafruit and supports font change. We are not using this LCD in our project because of the cost factor, which is quite expensive.
