### ISSUE TITLE
 interfacing the project to the cloud

### ISSUE THREAD

**Issue by mikeshams** [karamjotkaur/capstone_project#11]
Harmandeep - What issues did you face interfacing the project to the cloud? How did you resolve them? Modify the charts as instructed.

**Comment by harmandeepsingh1234** [comment]
While interfacing the project to the cloud I faced several issues which are listed below : 

1. Firstly the beaglebone black doesn’t have inbuilt wifi functionality so esp32 wifi module was used to access ThingSpeak as the cloud service and I used arduino ide for programming esp32 but the first issue I faced was that I checked the list of available boards in arduino ide and I didn’t find any board for esp32.                                        


Resolving the issue:- Then i researched on internet for how to add the esp32 board in arduino ide and then I found a useful link which has all the steps to add the board in the ide and I followed all the steps and then i was able to add the esp32 board in my arduino ide. The link for adding the board is given as follows : https://randomnerdtutorials.com/installing-the-esp32-board-in-arduino-ide-mac-and-linux-instructions/


2. Then after installing the esp32 board in arduino ide the next issue i faced was that when I connected the esp32 to my laptop using USB cable then I was not able to select the port for my board and the port is required to load the code into the board.                                                 


Resolving the issue:- So to resolve this issue i researched on internet and i came to know that i need to install a driver in my laptop for esp32 board to support USB communication. Then I found the correct driver which was CP2102 USB to UART bridge controller and then after installing it I was able to select my port. The reference for this link is provided as follows:- https://techexplorations.com/guides/esp32/begin/cp21xxx/

3. Since I am using UART communication between beaglebone black and esp32 so at first i was not able to receive and send any data then I checked the wires and everything looks perfect to me.                                                   


Resolving the issue:- After doing some research i came to know that The BBB by default has the UART pins set as normal GPIO pins so they need to be changed to UART pins first before they will work. This was the reason I was not able to get the UART communication working so then I figured it out and followed the steps and enabled the UART1 pins on Beaglebone black and then I was able to get the UART protocol working. The reference for this is provided as follows:- https://electronics.trev.id.au/2018/02/09/get-uart-serial-ports-working-beaglebone-black/

4. When I was loading the code in esp32 board then I got this error message- “ Failed to execute script esptool does not exist or your board is not connected “.           


Resolving this issue:- Then i checked on the internet for this error message and i came to know that I need to select the correct COM port in which the esp32 is connected and I checked that it was COM5 and I selected that and then this error was resolved. 

5. When flashing the code in esp32 I got another error message-“ Request Timed out waiting for packet header”.                        


Resolving this issue:- Then i checked on the internet for this error message and i came to know that I need to remove the esp32 UART pins wires connected with the beaglebone black and also the beaglebone black should be unplugged from laptop before loading the code in esp32. I did this method and it worked and I was able to load the code in esp32. 

6. Sometimes my esp stops executing the program and the data stops uploading on cloud.                                                    

Resolving this issue:- I checked on internet and came to know that I need to press reset button on esp32 to start the execution every time i run the code from beaglebone black. 


7.. When I was trying to upload a new sketch to esp32 and in the middle of uploading the code the process was getting stopped by itself and arduino ide stops the connection there. I checked the settings and everything was fine.

Resolving the issue:- after doing research i came to know that sometimes my esp32 doesn’t automatically go into boot/flashing mode and It happens because Arduino IDE fails to send the right command sequence to put the ESP32 automatically in flashing/uploading mode. 
So I followed these steps first :- 1. Press the “Upload” button in the Arduino IDE to upload a new sketch. 2. After you see the  “Connecting….” message in your Arduino IDE, release the finger from the “BOOT” button.  3. After that, you should see the “Done uploading” message . 



8. When i was executing the program I was getting redundant or garbage values and sometimes the previous data was being repeated then I checked the connections were fine so i know that it would be an issue inside the code

Resolving the issue:- I used debugging strategy to check which parts are giving me the errors and then it helped me to know which part is not being executed and what i need to do to modify.I used DEBUG preprocessor macro to check which parts are not being executed to help me identify the issue and resolve it. 



I modify the charts and made 2 fields – first is for number of people inside the store and the second field is for number of people detected with high temperature.

![image](https://user-images.githubusercontent.com/54857772/101175752-8b0b8a80-3613-11eb-80eb-ae32643b0aaf.png)
