### ISSUE TITLE
PCB Design

### ISSUE THREAD

**Issue by mikeshams** [karamjotkaur/capstone_project#12]
Harmandeep - 1) Did you decide to use a double sided PCB? Wht?

**Comment by harmandeepsingh1234** [comment]
1.	In our project we are not using any double sided PCB. We are using the single sided zero PCB, the reason for the same being that the cost of double sided is expensive as compared to that of the single sided zero PCB.

2.	Since we have components which can fit together on single side of the PCB thus using a double sided would be unnecessary in our project.

3.	Furthermore, it is easier to solder on single sided PCB as compared to a double sided PCB.

4.	As our system is not that large or complicated so using a single side PCB we can trace all the paths conveniently via a soldering or via wiring as required by our design.

5.	Lastly, I would say that I agree that the double sided PCB can shrink the size of the product but since the size of the PCB doesn’t matter here thus we can use it conveniently. Also, we do not intend to use the PCB as shield for any device thus we can use single sided PCB.
