### ISSUE TITLE
Ultrasonic Sensor Interfacing

### ISSUE THREAD

**Issue by mikeshams** [karamjotkaur/capstone_project#4]
Gurdeep- 1) What issues did you face when interfacing the ultrasonic sensors? 2) How did you resolve them?

**Comment by gurdeepsingh17** [comment]
During the interfacing of ultrasonic sensor with beaglebone black following issues were faced:-
1) For using the GPIO pins of beaglebone, we have  to use iobb.h library. Initially I downloaded the library from github and tried to run the code. But it was giving error. So I have to install the library in beaglebone first, after that the code was working well.
2) After printing a line, I tried to give more delay so that it can stays on screen for sometime but i was unable to do it in single command because the maximum delayed that can be set is 999 so I used the delay function multiple times to give more delay.
3) There was an error when I was trying to move files from my host machine to beaglebone through putty terminal. To overcome that problem i downloaded winSCP app that directly moves the file from host machine to distance machine by just drag and drop.
