### ISSUE TITLE
Interfacing Temperature sensor & Buzzer

### ISSUE THREAD

**Issue by mikeshams** [karamjotkaur/capstone_project#5]
Karamjot -  1) What issues did you face when interfacing the temperature sensor 2) How did you resolve them?  3) What issues did you face when interfacing the buzzer 4) How did you resolve them? 5) Demonstrate your tasks

**Comment by karamjotkaur** [comment]
I tried to interface Temperature and Buzzer with Beaglebone Black. I was not successful in completing this task as the sensor got damaged. I have ordered the new one, but have not received it yet. I will be able to demonstrate the interfacing once I receive the component. Besides, the following are the issues that I faced during this interfacing:
1. Initially, I faced some problems with installing iobb.h library. I was downloading the wrong files. Then I searched and found one website with commands and a link to download and install a library. I followed all the steps, and I was successful in compiling my code in Beaglebone black.
2. Moreover, I had a problem with the sensors' pins as some of the websites were showing the wrong pinout. Then I realized I should follow the datasheet, and from that, I got proper pinout. Also, due to the wrong connections, the sensor is damaged, and it is giving the wrong reading now.


As for the buzzer, it working fine alone but I will come to know about its operation when I get the sensor and run the code.

**Comment by karamjotkaur** [comment]
After receiving the temperature sensor, I tried the interfacing. This time, I was successful. The only issue I faced is that the headers of the sensors were not soldered. Moreover, there was a power cut in my area, so I could not solder it within a day. Once I completed the soldering, the sensor is detecting temperature and the buzzer turns on at a higher temperature.
